apiVersion: v1
kind: Service
metadata:
  name: counter-app-service
spec:
  type: NodePort
  selector:
    app: counter-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080   # 固定端口，方便记忆
