name: Build and Push Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      user: docker/login-action@v2
      with:
        username: ${{ secrets.taojie }}
        password: ${{ secrets.Tj20010909 }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: taojie1/counter-app:latest
